name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'branch-*' ]
    paths-ignore:
      - monitor-ui/**

jobs:
  build:
    env:
      INTERFACE_NAME: "eth0"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.17
          apps: sbt sbtn
      - uses: coursier/cache-action@v6.3

      - name: Install Redis
        run: sudo apt-get install redis-server

      - name: Install Kotlin
        run: |
          curl -s https://get.sdkman.io | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          sudo ln -s $(which kotlinc) /usr/local/bin/kotlinc

      - name: Build
        working-directory: integration
        run: |
          sbtn clean
          sbtn scalafmtCheck

      - name: Check port
        run: |
          sudo service redis-server stop
          echo "CHECKING IF FREE PORT:6379"
          ps aux | grep 6379

      - name: Tests
        working-directory: integration
        run: sbt -DenableFatalWarnings=true -DgenerateStoryReport=true test:test
      
      - name: Generate RTM
        working-directory: integration
        run: cs launch --channel https://raw.githubusercontent.com/tmtsoftware/osw-apps/master/apps.json rtm:0.3.0 -- target/RTM/testStoryMapping.txt ../tools/RTM/storyRequirementMapping.csv target/RTM/testRequirementsMapping.txt

      - name: Upload RTM
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Integration RTM
          path: integration/target/RTM

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
